Saffron/Models/Household.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Saffron.Models
{
    public class Household
    {
        //  internal fields
        public int Id { get; set; }
        public string Name { get; set; }

        // one to one relationships


        // one to many and many to many relationships
        public Household()
        {
            this.Accounts = new HashSet<Account>();
            this.Budgets = new HashSet<Budget>();
            this.Categories = new HashSet<Category>();
            this.Users = new HashSet<ApplicationUser>();
            this.Invitees = new HashSet<Invitee>();
        }

        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<ApplicationUser> Users { get; set; }
        public virtual ICollection<Invitee> Invitees { get; set; }

    }
}

Saffron/Controllers/HouseholdsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Saffron.Models;
using Microsoft.AspNet.Identity;
using System.Configuration;
using SendGrid;

namespace Saffron.Controllers
{
    public class HouseholdsController : Controller
    {
        
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Households
        public ActionResult Index()
        {
            return View(db.Household.ToList());
        }

        // GET: Households/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Household household = db.Household.Find(id);
        //    if (household == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(household);
        //}

        // GET: Households/Create
        //public ActionResult Create()
        //{
        //    Household newHousehold = new Household();

            
        //}

        //============================== Create and Join Household ============================================================================

        // POST: Households/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.        
        
        public ActionResult Create()
        {
            Household household = new Household();
            ApplicationUser currUser = db.Users.Find(User.Identity.GetUserId());
            household.Users.Add(currUser);
            household.Name = currUser.LastName;

            if (ModelState.IsValid)
            {
                db.Household.Add(household);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return RedirectToAction("Index", "Home");
        }

//============================== Leave Household ============================================================================


        // GET: Households/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Household household = db.Household.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }
            return View(household);
        }

        // POST: Households/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Household household)
        {
            if (ModelState.IsValid)
            {
                db.Entry(household).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(household);
        }



 //============================== Leave Household ============================================================================

        // GET: Households/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Household household = db.Household.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }
            if (household.Users.Count > 1)
            {
                ViewBag.HouseholdMembers = new SelectList(household.Users, "Id", "DisplayName");
                
            }
            
            return View(household);
        }

 


        // POST: Households/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Household household = db.Household.Find(id);
            ApplicationUser currUser = db.Users.Find(User.Identity.GetUserId());
            household.Users.Remove(currUser);

            
            if (ModelState.IsValid)
            {
                db.Entry(household).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Index", "Home");
        }
//============================== Invite to Household ============================================================================


        public ActionResult Invite ()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Invite (string Email)
        {
            if(db.Users.Count(a=>a.Email == Email) > 0)
            {
                return RedirectToAction("Exists");
            }
            Invitee newInvitee = new Invitee();
            var apiKey = ConfigurationManager.AppSettings["SendGridAPIKey"];
            var from = ConfigurationManager.AppSettings["ContactEmail"];
            ApplicationUser currUser = db.Users.Find(User.Identity.GetUserId());
            SendGridMessage myMessage = new SendGridMessage();
            myMessage.AddTo(Email);
            myMessage.From = new System.Net.Mail.MailAddress("DoNotReply@Saffron.com");
            myMessage.Subject = "An Invitation From Saffron: Budgeting and Financial Management";
           

            newInvitee.Email = Email;
            newInvitee.BeenUsed = false;
            newInvitee.HouseholdId = (int)currUser.HouseholdId;
            if (currUser.HouseholdId.HasValue) { newInvitee.HouseholdId = (int)currUser.HouseholdId; }

            if (ModelState.IsValid)
            {
                db.Invitee.Add(newInvitee);
                db.SaveChanges();
                int Id = newInvitee.Id;                                                                         
                myMessage.Html = "You have been invited to join " + currUser.DisplayName + "'s household.  Click this link to Register and Join: <a href = \"http://arowan-budgeter.azurewebsites.net/Account/ExternalRegister/" + Id + "\"> Join the Household </a>";
                var transportWeb = new Web(ConfigurationManager.AppSettings["SendGridAPIKey"]);
                transportWeb.DeliverAsync(myMessage);
                return RedirectToAction("Overview", "Home");

            }

            return RedirectToAction("Overview", "Home");

        }

        public ActionResult Exists ()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Saffron/Views/Households/Create.cshtml
@model Saffron.Models.Household

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Household</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Saffron/Views/Households/Delete.cshtml
@model Saffron.Models.Household
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework

@{
    ViewBag.Title = "Delete";
}

<h2>Leaving So Soon?</h2>

<h3>Are you sure you want to leave this household?</h3>
<div>
    <hr />


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
            <div class="form-actions">
            @if (Model.Users.Count > 1)
            {
                <h4>Select User to be Head Of Household:</h4>
                @Html.DropDownList("HouseholdMembers", null, htmlAttributes: new { @class = "form-control" })
            }

            


            <input type="submit" value="Leave Household" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index", "Home")
        </div>
    }
</div>

Saffron/Views/Households/Details.cshtml
@model Saffron.Models.Household

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Household</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Saffron/Views/Households/Edit.cshtml
@model Saffron.Models.Household

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Household</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Saffron/Views/Households/Exists.cshtml
@{
    ViewBag.Title = "Exists";
}



<div class="container">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">

                        <div class="ibox-tools">

                            <ul class="dropdown-menu dropdown-user">
                                <li>
                                    <a href="#">Config option 1</a>
                                </li>
                                <li>
                                    <a href="#">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                        <h2>That User Already Exists</h2>
                    </div>
                    <div class="ibox-content">
                        That User Already Exists!!! <br />
                        @Html.ActionLink("Return To Invite","Invite") <br />
                        @Html.ActionLink("Return To Register", "Register", "Account")
                    </div>
                </div>
            </div>  
        </div>
    </div>  
</div>

Saffron/Views/Households/Index.cshtml
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using Saffron.Models

@{
    var Manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
    var currUser = Manager.FindById(User.Identity.GetUserId());
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h2>Household Management</h2>
                </div>
                <div class="ibox-content">

                    <div class="container">

                        @if (currUser != null)
                        {
                            if (currUser.HouseholdId == null)
                            {
                                <div class="col-md-4">
                                    
                                    @Html.ActionLink("Create a New Household", "Create", "Households", null, new { @class = "btn btn-primary" })

                                </div>
                            }
                            if (currUser.HouseholdId != null)
                            {
                                <div class="col-md-4">
                                    
                                    <div class="row">
                                        @Html.ActionLink("Leave Household", "Delete", "Households", new { id = currUser.HouseholdId }, new { @class = "btn btn-primary" })
                                    </div>
                                   
                                    @if (currUser.HeadOfHousehold == true)
                                    {
                                        <div class="row">
                                            @Html.ActionLink("Invite Another User", "Invite", "Households", null, new { @class = "btn btn-primary" })
                                        </div>
                                        
                                        <div class="row">
                                            @Html.ActionLink("Change Household Name", "Edit", "Households", new { id = currUser.HouseholdId }, new { @class = "btn btn-primary" })
                                        </div>
                                         }
                                </div>
                            }
                                <div class="col-md-6 well" style="text-align:center">
                                    <h2> Current Household Members </h2>
                                        <table>
                                            <thead>
                                                <tr>
                                                    <th class="col-md-6">Name</th>
                                                    <th class="col-md-6">Email</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var user in currUser.Household.Users)
                                                {
                                                    <tr>
                                                        <td>@user.DisplayName</td>
                                                        <td>@user.Email</td>
                                                    </tr>
                                                    
                                                }
                                            </tbody>
                                        </table>
                                    
                                </div>
                            
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Saffron/Views/Households/Invite.cshtml
@{
    ViewBag.Title = "Invite";
}

<h2>Invite someone to your household</h2>

<div class="container">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Budget Items</h5>
                        <div class="ibox-tools">
                            
                            <ul class="dropdown-menu dropdown-user">
                                <li>
                                    <a href="#">Config option 1</a>
                                </li>
                                <li>
                                    <a href="#">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        @using (Html.BeginForm("Invite", "Households", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="row">
                                <div class="col-md-2">  Email  </div>
                                <input class="form-control col-md-12d" type="email" name="email" />
                                <input type="submit" class="col-md-10 btn btn-primary" value="Send Invite" />
                            </div>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>