Saffron/Controllers/BudgetsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Saffron.Models
{
   

    public class BudgetsController : Controller
    {
        

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Budgets
        public ActionResult Index(DateTime? start, DateTime? end)
        {
            if (start == null)
            {
                start = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
            }

            if (end == null)
            {
                end = new DateTime(DateTime.Now.Year, DateTime.Now.Month + 1, 1);
            }

            ApplicationUser currUser = db.Users.Find(User.Identity.GetUserId());
            if (currUser == null) { return RedirectToAction("Login", "Account"); }
            BudgetTransactionViewModel viewModel = new BudgetTransactionViewModel();
            DateTime currMonth = DateTime.Today.AddDays(-30);

            //viewModel.Budgets = currUser.Household.Budgets.ToList();
            viewModel.BudgetItems = db.BudgetItem.Where(o => o.Budget.HouseholdId == currUser.HouseholdId).OrderBy(o => o.Category.Name).ToList();
            viewModel.Transactions = db.Transaction.Where(o => o.Account.HouseholdId == currUser.HouseholdId && o.Date < end && o.Date > start).ToList();
            viewModel.GraphData = Stringify(viewModel.BudgetItems);
            viewModel.GraphData = AddTransactions(viewModel.GraphData, viewModel.Transactions);
           
            return View(viewModel);
        }


        //========================== Graph Helper ========================================

        private List<BudgetViewItem> Stringify(List<BudgetItem> items)
        {
            List<BudgetViewItem> returnObj = new List<BudgetViewItem>();
           
            
            foreach (var item in items)
            {
                BudgetViewItem itemList = CloneObject(item);         
                
                returnObj.Add(itemList);
               
            }

            return returnObj;
        }

        private BudgetViewItem CloneObject(BudgetItem item)
        {
            var javaScriptSerializer = new JavaScriptSerializer();
            BudgetViewItem itemList = new BudgetViewItem();
            itemList.BudgetItemId = item.Id;
            itemList.CategoryName = item.Category.Name;
            itemList.CategoryId = item.CategoryId;
            itemList.BudgetTotal = item.Amount;
            itemList.TotalValue = javaScriptSerializer.Serialize(item.Amount);
            return itemList;
        }

        private List<BudgetViewItem> AddTransactions(List<BudgetViewItem> items, List<Transaction> transactions)
        {

            for (int i = 0; i < items.Count; i++)
            {
                items[i] = LinkTransactionsItem(items[i], transactions);
            }   
                
            

            return items;
        }

        private BudgetViewItem LinkTransactionsItem(BudgetViewItem item, List<Transaction> transactions)
        {
            var javaScriptSerializer = new System.Web.Script.Serialization.JavaScriptSerializer();

            float sum = 0;
            int count = 0;

            foreach (var iTransaction in transactions)
            {


                if (item.CategoryId == iTransaction.CategoryId)
                {
                    if (iTransaction.TypeTransactionId == 1 || iTransaction.TypeTransactionId == 4)
                    {
                        sum -= iTransaction.Amount;  //  Deposits are negative spending
                        count++;
                    }

                    if (iTransaction.TypeTransactionId == 2 || iTransaction.TypeTransactionId == 3)
                    {
                        sum += iTransaction.Amount;  //  Withdrawls are positive spending
                        count++;
                    }
                }
            }

            sum = (sum / item.BudgetTotal) * 100;
            item.SumValue = javaScriptSerializer.Serialize(sum);
            item.TransactionCount = count;
            item.TotalValue = javaScriptSerializer.Serialize(100);
            return item;
        }

        public ActionResult GraphTest()
        {
            return View();
        }

        // GET: Budgets/Details/5
        public ActionResult Details(int? id)
        {
            ApplicationUser currUser = db.Users.Find(User.Identity.GetUserId());
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BudgetItem budgetItem = db.BudgetItem.Find(id);
            if (budgetItem == null)
            {
                return HttpNotFound();
            }
            BudgetViewItem viewItem = CloneObject(budgetItem);
            //viewItem.CategoryName = budgetItem.Category.Name;
            //viewItem.BudgetItemId = budgetItem.Id;
            //viewItem.BudgetTotal = budgetItem.Amount;         
            ViewBag.Transactions = db.Transaction.Where(o => o.Account.HouseholdId == currUser.HouseholdId && o.CategoryId == budgetItem.CategoryId).ToList();
            viewItem = LinkTransactionsItem(viewItem, ViewBag.Transactions);  

            return View(viewItem);
        }

        // GET: Budgets/Create
        public ActionResult Create()
        {
            ApplicationUser currUser = db.Users.Find(User.Identity.GetUserId());
            ViewBag.HouseholdId = currUser.HouseholdId;
            if(currUser.Household.Budgets.Count() == 0)
            {
                Budget newBudget = new Budget();
                newBudget.HouseholdId = (int)currUser.HouseholdId;
                newBudget.Name = currUser.LastName;
                db.Budget.Add(newBudget);
                db.SaveChanges();
            }
            ViewBag.BudgetId = currUser.Household.Budgets.First().Id;
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");
            ViewBag.RepeatFrequencyId = new SelectList(db.RepeatFrequency, "Id", "Frequency");
            
            return View();
        }

        // POST: Budgets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DateTime DayOfMonth, int RepeatFrequencyId, int CategoryId, float Amount, int BudgetId)
        {
            // check for existing budget for set category
            ApplicationUser currUser = db.Users.Find(User.Identity.GetUserId());
            int categorySum = 0;
            int budgetItemId = 0;
            foreach (Budget userBudget in currUser.Household.Budgets)
            {
                int count = 0;
                count = db.BudgetItem.Where(i => i.CategoryId == CategoryId && userBudget.Id == i.BudgetId).Count();
                categorySum += count;
                if (count > 0)
                {
                    budgetItemId = db.BudgetItem.Where(i => i.CategoryId == CategoryId && userBudget.Id == i.BudgetId).FirstOrDefault().Id;
                }
            }

            if (categorySum > 0)
            {
                return RedirectToAction("CreateError", new { id = budgetItemId });
            }
            BudgetItem budget = new BudgetItem();

            budget.DayOfMonth = DayOfMonth.Day;
            budget.BudgetId = BudgetId;
            budget.RepeatFrequencyId = RepeatFrequencyId;
            budget.CategoryId = CategoryId;
            budget.Amount = Amount;

            if (ModelState.IsValid)
            {
                db.BudgetItem.Add(budget);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

           
            ViewBag.HouseholdId = currUser.HouseholdId;
            ViewBag.BudgetId = currUser.Household.Budgets.First().Id;
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");
            ViewBag.RepeatFrequencyId = new SelectList(db.RepeatFrequency, "Id", "Frequency");
            return View();
        }

        public ActionResult CreateError(int? id)
        {
            ViewBag.Id = id;
            return View();
        }

        // GET: Budgets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BudgetItem budgetItem = db.BudgetItem.Find(id);
            if (budgetItem == null)
            {
                return HttpNotFound();
            }

            ApplicationUser currUser = db.Users.Find(User.Identity.GetUserId());
            ViewBag.HouseholdId = currUser.HouseholdId;
            ViewBag.BudgetId = currUser.Household.Budgets.First().Id;
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", budgetItem.CategoryId);
            ViewBag.RepeatFrequencyId = new SelectList(db.RepeatFrequency, "Id", "Frequency", budgetItem.RepeatFrequencyId);
            return View(budgetItem);
        }

        // POST: Budgets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( int CategoryId, float Amount, int RepeatFrequencyId, int DayOfMonth, int BudgetId, int Id)
        {
            BudgetItem budgetItem = new BudgetItem();
            budgetItem.Amount = Amount;
            budgetItem.CategoryId = CategoryId;
            budgetItem.RepeatFrequencyId = RepeatFrequencyId;
            budgetItem.DayOfMonth = DayOfMonth;

Saffron/Views/Shared/_BudgetSummary.cshtml
@using Saffron.Models
@model  BudgetSummaryViewModel


    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <div class="ibox-tools">
                            <ul class="dropdown-menu dropdown-user">
                                <li>
                                    <a href="#">Config option 1</a>
                                </li>
                                <li>
                                    <a href="#">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                        <div class="container">
                            <div class=" row">
                                <div class="col-md-12"><h3>Budget Summary</h3>  </div>   @* Header *@
                            </div>
                        </div>
                      
                        <a href="@Url.Action("Create", "Budgets")" style="margin-left: 30px"><i class="fa fa-plus btn btn-warning">   Create a New Budget</i></a>

                    </div>
                    <div class="ibox-content">
                        <div class="ct-chart" id="a1"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script src="~/Scripts/jquery-2.1.1.js"></script>

    <script>

        $(document).ready(function () {

            @{
@*<text>
                            new Chartist.Bar('#a1', {
                              labels: [1, 2, 3],
                              series: [[{ meta: 'description', value: 1 }, { meta: 'description', value: 5 }, { meta: 'description', value: 3 }],
                                  [{ meta: 'other description', value: 2 },{meta: 'other description', value: 4},{meta: 'other description', value: 2}]]}, 
                                {
                              low: 0,
                              high: 8,
                              fullWidth: true,
                              plugins: [
                                Chartist.plugins.tooltip()
                              ]
                            });
</text>*@
                //string data = "{ labels: ['Spent', 'Budgeted'], series: [ [" + GraphItem.SumValue + "], ["+ GraphItem.TotalValue + "] ]}";
                //string options = "{ high: 100, low: 0, seriesBarDistance: 30, horizontalBars: true, axisY: { offset: 50 } }";
                string dataLabels = "{ " + Model.Labels + ", ";
                string dataSeries = Model.Series + ", ";
                string dataTotal = Model.SeriesTotal + " ] }";
                string options = "{" + Model.Options + " }";

                string Chartstring1 = "new Chartist.Bar('#a1',";
                string Chartstring2 = @dataLabels + "  ";
                string Chartstring21 = @dataSeries + "  ";
                string Chartstring22 = @dataTotal + " , ";
                string Chartstring3 = @options + ")";

            <text>
            @Html.Raw(Chartstring1)
            @Html.Raw(Chartstring2)
            @Html.Raw(Chartstring21)
            @Html.Raw(Chartstring22)
            @Html.Raw(Chartstring3)
            </text>
          }



        })

    </script>

Saffron/Views/Shared/_EditTransactionPartial.cshtml
@using Saffron.Models
@model Transaction

    <div >
        @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "editForm", action = "javascript:submitEditTransactionForm()" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id);

            <table class="table">
                <thead>
                    <tr>
                        <th>Account</th>
                        <th>Category</th>
                        <th>Type</th>
                        <th>Date</th>
                        <th>Amount</th>
                        @*<th>Reconciled? </th>*@

                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Html.DropDownList("AccountId", null, htmlAttributes: new { @class = "form-control" }) </td>
                        <td>@Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })</td>
                        <td>@Html.DropDownList("TypeTransactionId", null,  htmlAttributes: new { @class = "form-control" })</td>
                        <td>@Html.Editor("Date", new { htmlAttributes = new { @class = "form-control datePicker" } })</td>
                        @*<td>@Html.Editor("Amount", new { htmlAttributes = new { @class = "form-control " } }, new { Amount = Model.Amount } )</td>*@
                        <td>@Html.EditorFor(m=>m.Amount)</td>
                        @*<td>@Html.CheckBox("Reconciled", false)</td>*@
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>
                            <button type="submit" class="btn btn-warning"> Save Edited Transaction </button>
                        </td>
                    </tr>
                </tbody>
            </table>
        }
    </div>
<script>
    $(function () {
        $(".datePicker").datepicker({ dateformat: "mm/dd/yy" });
    });
</script>

Saffron/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        <i class="fa fa-bars"></i>  Saffron
    </div>
    <div>
        <strong>Copyright</strong> Aaron Rowan &copy; 2015-2017
    </div>
</div>

Saffron/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="~/Images/favicon.png" />
    <title>Rowan | @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")
</head>
<body>

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        @Html.Partial("_Navigation")

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/metsiMenu")
    @Scripts.Render("~/plugins/pace")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")
    @RenderSection("scripts", required: false)
</body>
</html>

Saffron/Views/Shared/_Navigation.cshtml
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using Saffron.Models
@if (Request.IsAuthenticated)
{
    var Manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
    var currUser = Manager.FindById(User.Identity.GetUserId());
    string displayName;

    if (String.Empty == currUser.DisplayName || currUser.DisplayName == null)
    {
        displayName = currUser.Email;
    }
    else { displayName = currUser.DisplayName; }

    ViewBag.displayName = displayName;
    ViewBag.currUser = currUser;
    if (currUser.Household.Accounts.Count > 0)
    {
        ViewBag.Accounts = currUser.Household.Accounts.ToList();
    }

}

<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">@ViewBag.displayName </strong>
                            </span> <span class="text-muted text-xs block"><i class="fa fa-gear"></i> <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li>@Html.ActionLink("My Account", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })</li>
                        <li>@Html.ActionLink("Change Password", "ChangePassword", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" }) </li>
                        @if (ViewBag.currUser != null)
                        {
                            if (ViewBag.currUser.HeadOfHousehold)
                            {
                                <li>@Html.ActionLink("Manage Household", "Index", "Households", null, new { title = "Manage" })</li>
                            }
                        }
                    </ul>
                </div>
            </li>
            <!---------Main Panel---------->

            @if (ViewBag.currUser != null && ViewBag.Accounts != null)
            {
                <li>
                    <a href="@Url.Action("Create", "BankAccounts")"><i class="fa fa-plus btn btn-warning">   Create New Account</i></a>
                </li>

                <li class="active">
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-dollar"></i> <span class="nav-label">Savings Accounts</span> </a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                {
                    if (account.AccountTypeId == 2)
                    {
                                <li>
                                    <h3>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id }, null)</h3>
                                    <h5> Balance = $@account.Balance</h5>
                                </li>
                            }
                        }
                    </ul>

                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-check-circle"></i> <span class="nav-label">Checking Accounts</span> </a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                {
                    if (account.AccountTypeId == 1)
                    {
                                <li>
                                    <h3>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id }, null)</h3>
                                    <h5> Balance = $@account.Balance</h5>
                                </li>
                            }
                        }
                    </ul>

                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-credit-card"></i> <span class="nav-label">Credit Cards</span> </a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                {
                    if (account.AccountTypeId == 5)
                    {
                                <li>
                                    <h3>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id }, null)</h3>
                                    <h5> Balance = $@account.Balance</h5>
                                </li>
                            }
                        }
                    </ul>

                </li>
                <li></li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-institution"></i> <span class="nav-label">Money Market</span> </a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                {
                    if (account.AccountTypeId == 3)
                    {
                                <li>
                                    <h3>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id }, null)</h3>
                                    <h5> Balance = $@account.Balance</h5>
                                </li>
                            }
                        }
                    </ul>

                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-certificate"></i> <span class="nav-label">Cert. Deposit</span> </a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                {
                    if (account.AccountTypeId == 6)
                    {
                                <li>
                                    <h3>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id }, null)</h3>
                                    <h5> Balance = $@account.Balance</h5>
                                </li>
                            }
                        }
                    </ul>

                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-line-chart"></i> <span class="nav-label">Investment</span> </a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                {
                    if (account.AccountTypeId == 4)
                    {
                                <li>
                                    <h3>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id }, null)</h3>
                                    <h5> Balance = $@account.Balance</h5>
                                </li>
                            }
                        }
                    </ul>

                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-pie-chart"></i> <span class="nav-label">Insurance</span> </a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                {
                    if (account.AccountTypeId == 7)
                    {
                                <li>
                                    <h3>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id }, null)</h3>
                                    <h5> Balance = $@account.Balance</h5>
                                </li>
                            }
                        }
                    </ul>

                </li>
                @*<li class="@Html.IsSelected(action: "Minor")">
                    <a href="@Url.Action("Minor", "Home")"><i class="fa fa-check-circle" <span class="nav-label">Checking Account</span></a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                        {
                            if (account.AccountTypeId == 1)
                            {
                                <li>
                                    <h3>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id })</h3>
                                    <h5> Balance = $@account.Balance</h5>
                                </li>
                            }
                        }
                    </ul>
                </li>*@
                @*<li class="@Html.IsSelected(action: "Minor")">
                    <a href="@Url.Action("Minor", "Home")"><i class="fa fa-pie-chart"></i> <span class="nav-label">Money Market</span></a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                        {
                            if (account.AccountTypeId == 3)
                            {
                                <li>
                                    <h4>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id })</h4>
                                    <h3> Balance = $@account.Balance</h3>
                                </li>
                            }
                        }
                    </ul>
                </li>
                <li class="@Html.IsSelected(action: "Minor")">
                    <a href="@Url.Action("Minor", "Home")"><i class="fa fa-line-chart"></i> <span class="nav-label">Investment</span></a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                        {
                            if (account.AccountTypeId == 4)
                            {
                                <li>
                                    <h4>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id })</h4>
                                    <h3> Balance = $@account.Balance</h3>
                                </li>
                            }
                        }
                    </ul>
                </li>
                <li class="@Html.IsSelected(action: "Minor")">
                    <a href="@Url.Action("Minor", "Home")"><i class="fa fa-check-circle"></i> <span class="nav-label">Credit Card</span></a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                        {
                            if (account.AccountTypeId == 5)
                            {
                                <li>
                                    <h4>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id })</h4>
                                    <h3> Balance = $@account.Balance</h3>
                                </li>
                            }
                        }
                    </ul>
                </li>*@
                @*<li class="@Html.IsSelected(action: "Minor")">
                    <a href="@Url.Action("Minor", "Home")"><i class="fa fa-check-circle"></i> <span class="nav-label">Cert. Deposit</span></a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                        {
                            if (account.AccountTypeId == 6)
                            {
                                <li>
                                    <h4>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id })</h4>
                                    <h3> Balance = $@account.Balance</h3>
                                </li>
                            }
                        }
                    </ul>
                </li>
                <li class="@Html.IsSelected(action: "Minor")">
                    <a href="@Url.Action("Minor", "Home")"><i class="fa fa-check-circle"></i> <span class="nav-label">Insurance</span></a>
                    <ul>
                        @foreach (var account in ViewBag.Accounts)
                        {
                            if (account.AccountTypeId == 7)
                            {
                                <li>
                                    <h4>@Html.ActionLink((string)@account.Institution.Name, "Details", "BankAccounts", new { id = @account.Id })</h4>
                                    <h3> Balance = $@account.Balance</h3>
                                </li>
                            }
                        }
                    </ul>
                </li>*@

            }

            @if (ViewBag.currUser != null && ViewBag.Accounts == null)
            {
                <li>
                    <a href="@Url.Action("Create", "BankAccounts")" style="margin-left: 10px"><i class="fa fa-plus btn btn-warning">   Create a New Account</i></a>
                </li>                
            }
        </ul>
    </div>
</nav>

Saffron/Views/Shared/_PartialTest.cshtml
<h3>@ViewBag.TestText</h3>

Saffron/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="nav navbar-nav">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Overview", "Overview", "Home")  </li>
                <li>@Html.ActionLink("Transactions", "Index", "Transactions")</li>
                <li>@Html.ActionLink("Budgets", "Index", "Budgets")</li>
            </ul>
            @*<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>*@
            @*<form role="search" class="navbar-form-custom" method="post" action="">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>*@
        </div>
        @Html.Partial("_LoginPartial")
    </nav>
</div>